---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
archives:
  - files:
      - LICENSE
    builds_info:
      group: root
      owner: root
      mode: 0755
    name_template: "dcjulian29.apps.cert-auth_{{ .Version }}_{{ .Os }}"
    format_overrides:
      - format: zip
        goos: windows
nfpms:
  - package_name: dcjulian29.apps.cert-auth
    homepage: https://github.com/dcjulian29/cert-auth/
    maintainer: Julian Easterling <julian@julianscorner.com>
    license: Apache 2.0
    dependencies:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    description: |-
      cert-auth provides the commands to run a certificate authority.
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
chocolateys:
  - name: dcjulian29.apps.cert-auth
    authors: Julian Easterling <julian@julianscorner.com>
    project_url: https://github.com/dcjulian29/cert-auth/
    copyright: 2023 Julian Easterling julian@julianscorner.com
    license_url: https://github.com/dcjulian29/cert-auth/blob/main/LICENSE
    require_license_acceptance: false
    bug_tracker_url: https://github.com/dcjulian29/cert-auth/issues
    description: |
      cert-auth provides the commands to run a certificate authority.
    dependencies:
      - id: docker-desktop
    api_key: "{{ .Env.CHOCO_API_KEY}}"
    source_repo: "https://www.myget.org/F/dcjulian29-chocolatey/"
    skip_publish: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
